// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZriBrx1oI0WnXRPUNpO_2Myn_-fKVog',
    appId: '1:1087128469381:web:55392f6c04f14ff5170eec',
    messagingSenderId: '1087128469381',
    projectId: 'cookly-mobile-app',
    authDomain: 'cookly-mobile-app.firebaseapp.com',
    storageBucket: 'cookly-mobile-app.firebasestorage.app',
    measurementId: 'G-NKPD1QDFDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyLcVjrep4XjcxX6BEZhmSIF7Vm-AuaU',
    appId: '1:1087128469381:android:5b1e7be1fa21dadd170eec',
    messagingSenderId: '1087128469381',
    projectId: 'cookly-mobile-app',
    storageBucket: 'cookly-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5EIwgZGk1Hvsq40WvXaRnwyB1uzHBIxg',
    appId: '1:1087128469381:ios:90f9491b62e6134e170eec',
    messagingSenderId: '1087128469381',
    projectId: 'cookly-mobile-app',
    storageBucket: 'cookly-mobile-app.firebasestorage.app',
    androidClientId: '1087128469381-su17g2os82v3jm2vkhmcpb62kuudnnjq.apps.googleusercontent.com',
    iosClientId: '1087128469381-atevqe5k585n33i5racp3t5iiop01ib7.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5EIwgZGk1Hvsq40WvXaRnwyB1uzHBIxg',
    appId: '1:1087128469381:ios:90f9491b62e6134e170eec',
    messagingSenderId: '1087128469381',
    projectId: 'cookly-mobile-app',
    storageBucket: 'cookly-mobile-app.firebasestorage.app',
    androidClientId: '1087128469381-su17g2os82v3jm2vkhmcpb62kuudnnjq.apps.googleusercontent.com',
    iosClientId: '1087128469381-atevqe5k585n33i5racp3t5iiop01ib7.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZriBrx1oI0WnXRPUNpO_2Myn_-fKVog',
    appId: '1:1087128469381:web:09eaf1abd60585aa170eec',
    messagingSenderId: '1087128469381',
    projectId: 'cookly-mobile-app',
    authDomain: 'cookly-mobile-app.firebaseapp.com',
    storageBucket: 'cookly-mobile-app.firebasestorage.app',
    measurementId: 'G-7WGEW1B8FC',
  );

}